### ISSUE TITLE
AIDE !!!

### ISSUE THREAD

**Issue by aerozik** [Caranille/Caranille#1]
Salut jerem !!
meilleur voeux pour commencer ;)
question : 
afin de pouvoir populariser ton engine est ce que tu serais interessé par la réalisation d'un mmorpg 
sur caranille complet avec design etc...
si oui hesite pas, je serais ravi de participer a ton projet ..
je commence a peine le php donc pour le code je suis limiter mais par contre j ai deja réaliser plusieurs
jeux et site web (j etudie egalement le javascript) et j ai une idee sympa de scenario et une communautée specifique qui pourrais apprecier ce genre de mmo text based

le faire seul est possible mais ce serait idiot de ne pas t aider si je le peux et de toute façon il me manque encore le pvp pour rendre le projet intéressant 
a++
aerozik

**Comment by finkiki** [comment]
Le site est down ?

**Comment by Caranille** [comment]
Bonjour,
Non il faut aller sur caranille.com le .fr a été racheté par un magasin de chaussure... tout ça car ce mois-ci je n'avais pas les moyens de payer le nom de domaine...

Et non Caranille n'est pas mort je suis juste actuellement en formation SQL pendant 2 mois encore minimum et je comptes bien me servir de ses connaissance pour Caranille.

Cordialement,
