### ISSUE TITLE
PSR-4 autoloading

### ISSUE THREAD

**Issue by tdutrion** [Caranille/Caranille#2]
Using `composer`, it is possible to set a PSR-4 autoloader to load classes instead of the `require`/`require_once`.

Coupled to a single entry point (`/index.php`), this autoloader can become really powerful. Have a look at Zend Expressive to see what routing librairies and so on they recommend, and probably Zend Framework 2 application skeleton to see the `.htaccess` and `index.php` files for instance.

**Comment by Caranille** [comment]
Thanks for your help, but i don't want to use this fucntion because my programme is for beginner and if i use it it more complex for the new developper

Regards
