### ISSUE TITLE
C'est pas censé être la V1 aujourd'hui?

### ISSUE THREAD

**Issue by finkiki** [Caranille/Caranille#8]
C'est pas censé être la V1 aujourd'hui?

**Comment by Caranille** [comment]
Bonjour,

Il n'y avais pas de news sur le site mais oui elle est bien sortie:
https://github.com/Caranille/Caranille/releases

Cordialement,

**Comment by Caranille** [comment]
Mais bon j'admet il y a un gros bug lors de l'installation. Sache que je suis en train de refaire entièrement le design pour le rendre responsive (Pour qu'il s'adapte en fonction de la taille de l'écran).

Je penses en avoir pour deux semaines pour refaire le design ce sera Caranille 1.1

**Comment by Caranille** [comment]
La version 1 est déjà sortie je peux donc clore le ticket 

Cordialement,
